language: php

php:
  - 7.2
  - 7.3

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - tests/data/travis/mongodb-setup.sh
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit $PHPUNIT_FLAGS

notifications:
  slack:
    -
      rooms:
        -
          secure: kJoidCSdvvKz3+08IFecOrsHRMAbdIywjptAzBYICMXSUxv/9R+MVZIg3OLHGBVrEkINZ9dJxoYTjsv4wNFxLio3BLwMXJYZzupCyrzT4F6wwQOh8CeI7/AzaJMTPAE8+dFPY6NVWxuThYXd8O9VxxTIMHgg5KDxL20yjnAFEXmqFd9S6abJfXXmnyIQMsDZpg8OyAKEdEyFYhJz+R+2hs3Srkb94/YiZPrEz0zAIcD/Yzbh4SSAOiG5Z3qdLGxTlbGTAxiFGugvMCJ6CoPr2ikiaLW0Wgs8w88aV29jcfJqPkoLwPJ37L5FBPad6tJZJPFDfUUNrLQKy2zDqIIua1WQX+n1BEk53k0Krk4xev6MGCg7lWLYQbqaN4tL0abtVs+enWEuda25u2vgzb7L1ppF0NSpq+eF9HcJ+N+tvtRNxzECYYBPJADklzLIkMTXpVo+KL6eeMqGEWLUUz4WGXVkKGGa6S+e+rVQstA1+MtgzQCHB0yQd6M6UdUGMfTSvg7L2EUve1hn6fbZXCI5FYgIymrrsPZ6Gh9WqExNL2X7G1mnIyZgw4GNE1tOlFvYieAzql5wvWHF9lyb0BaPzD14EloGMCovzXbOMQt65vbutep5EQdeo+yiZ9wgYv+M7ZIahk+6WqqpjgX0NESojmMsPSjcTvHm0Hi39RL3oOU=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: VEDRsv0A857KMjLiIG27hfHMwh/95uCrEB5GMRqF+nwuHpUXZGQdgJHoGDbCss6EVfsC7xdmA/XWXjWZ5nTe+NFWm5sKhftEMR558lKHEsSIWs98vPQWVlZXqmjd9iVB8NkZvma3uIbofO+lWM+DW5nCqNFM0OxOZgFDb8kEMYN7SPh74TqZKvLAj/9Sklq5ZSyo78pXJ0y3QWDduo/Ju/PxjZ3q7/F/j9K+l58xgbHuJ6cgEAlP426nnBpSC94xN7N3ftUKWc9Bg6uHT2Pu76D16e1iD9A5zDWFGWRpwmr1J5rq12eV3DC0IXel0vHCjKWlKcrFKcrjSRAdU/uxxxFS9i1vPjkcW9xUCzgroEZcVfBSg0KJsCQghNU7d7kJWNT81I4qJl/4R3aJLJLOM7pyt0MMYaB5glavU3DgPC8zjURnBeccYVrOou8rbhLKwujBH4kp/u/i486K1TZb/s2tqTOGS9dAn4M/3oBR34fOF5/XDtmuW9fppLN5f/MUSGGEIx3lzH7oLRgXBf5zUGTR98ekk65ZBagvblY+M70V/5hm/jYLIZYTMTe1nX0awM4KdwDi1UiUW0c6wFB806iwOFiUx9urxdNLlDAGDN6aPydFBtUiO6R85YOmzr8rh/IjufWhmRPKH05Z9M6F5FH099dh2vS8Ai3awosvyEc=
      on_success: never
      on_failure: always
      on_pull_requests: false
